plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'fabric-loom'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'sigil-testmod'
        enableGameTests = true
        enableClientGameTests = false
        eula = true
    }
}

processResources {
    filesMatching('fabric.mod.json') {
        expand project.properties
    }
}

processGametestResources {
    filesMatching('fabric.mod.json') {
        expand project.properties
    }
}

java {
    withSourcesJar()
    withJavadocJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    from('LICENSE')
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "qf-repo"
            url = uri("https://repo.biryeong.kim/releases/")
        }
    }
}
