name: Publish to Maven

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify
        run: ./gradlew build runGameTest --no-daemon

      - name: Deploy
        run: ./gradlew publish --no-daemon
        env:
          BIRYEONG_REPO_USERNAME: ${{ secrets.BIRYEONG_REPO_USERNAME }}
          BIRYEONG_REPO_PASSWORD: ${{ secrets.BIRYEONG_REPO_PASSWORD }}
